version: '3.8'
services:
  produto-db:
    image: postgres:15
    container_name: produto_postgres
    environment:
      POSTGRES_DB: ProdutoDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Senha123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - produto-network

volumes:
  postgres_data:

networks:
  produto-network:
    driver: bridge